/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as TentangKamiRouteImport } from './routes/tentang-kami'
import { Route as SyaratKetentuanRouteImport } from './routes/syarat-ketentuan'
import { Route as StudentRouteImport } from './routes/student'
import { Route as SearchOldRouteImport } from './routes/search-old'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginNewRouteImport } from './routes/login-new'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KebijakanPrivasiRouteImport } from './routes/kebijakan-privasi'
import { Route as HubungiKamiRouteImport } from './routes/hubungi-kami'
import { Route as DevRouteImport } from './routes/dev'
import { Route as DebugAuthRouteImport } from './routes/debug-auth'
import { Route as ClientRouteImport } from './routes/client'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as BecomeAnInstructorRouteImport } from './routes/become-an-instructor'
import { Route as ArticleRouteImport } from './routes/article'
import { Route as AksesibilitasRouteImport } from './routes/aksesibilitas'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as VerifyUuidRouteImport } from './routes/verify.$uuid'
import { Route as StudentWishlistRouteImport } from './routes/student.wishlist'
import { Route as StudentSettingsRouteImport } from './routes/student.settings'
import { Route as StudentProfileRouteImport } from './routes/student.profile'
import { Route as StudentNotificationSettingsRouteImport } from './routes/student.notification-settings'
import { Route as StudentNotificationRouteImport } from './routes/student.notification'
import { Route as StudentDashboardRouteImport } from './routes/student.dashboard'
import { Route as CourseCourseSlugRouteImport } from './routes/course/$courseSlug'
import { Route as CategoriesSlugRouteImport } from './routes/categories.$slug'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AdminProfileRouteImport } from './routes/admin/profile'
import { Route as AdminNotificationRouteImport } from './routes/admin/notification'
import { Route as AdminGalleryRouteImport } from './routes/admin/gallery'
import { Route as AdminFeaturedCoursesRouteImport } from './routes/admin/featured-courses'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminBannersRouteImport } from './routes/admin/banners'
import { Route as StudentOrderIndexRouteImport } from './routes/student.order.index'
import { Route as InstructorApplyIndexRouteImport } from './routes/instructor/apply/index'
import { Route as AdminUserIndexRouteImport } from './routes/admin/user/index'
import { Route as AdminRoleIndexRouteImport } from './routes/admin/role/index'
import { Route as AdminQuizIndexRouteImport } from './routes/admin/quiz/index'
import { Route as AdminPromotionIndexRouteImport } from './routes/admin/promotion/index'
import { Route as AdminOrganizationIndexRouteImport } from './routes/admin/organization/index'
import { Route as AdminOrderIndexRouteImport } from './routes/admin/order/index'
import { Route as AdminInstructorApplicationsIndexRouteImport } from './routes/admin/instructor-applications/index'
import { Route as AdminGuideIndexRouteImport } from './routes/admin/guide/index'
import { Route as AdminCourseIndexRouteImport } from './routes/admin/course/index'
import { Route as AdminArticleIndexRouteImport } from './routes/admin/article/index'
import { Route as StudentOrderUuidRouteImport } from './routes/student.order.$uuid'
import { Route as StudentLearnCourseUuidRouteImport } from './routes/student.learn.$courseUuid'
import { Route as InstructorApplyStatusRouteImport } from './routes/instructor/apply/status'
import { Route as CertificateVerifyPreviewRouteImport } from './routes/certificate/verify/preview'
import { Route as CertificateVerifyUuidRouteImport } from './routes/certificate/verify/$uuid'
import { Route as B2bActivateInvitationUuidRouteImport } from './routes/b2b/activate.$invitationUuid'
import { Route as AdminSettingPlatformRouteImport } from './routes/admin/setting/platform'
import { Route as AdminSettingPaymentMethodRouteImport } from './routes/admin/setting/payment-method'
import { Route as AdminSettingNotificationPreferencesRouteImport } from './routes/admin/setting/notification-preferences'
import { Route as AdminSettingAppRouteImport } from './routes/admin/setting/app'
import { Route as AdminQuizQuizUuidRouteImport } from './routes/admin/quiz/$quizUuid'
import { Route as AdminPromotionCreateVoucherRouteImport } from './routes/admin/promotion/create-voucher'
import { Route as AdminPromotionCreateRouteImport } from './routes/admin/promotion/create'
import { Route as AdminPromotionCouponRouteImport } from './routes/admin/promotion/coupon'
import { Route as AdminOrganizationTagRouteImport } from './routes/admin/organization/tag'
import { Route as AdminOrganizationOrgUuidRouteImport } from './routes/admin/organization/$orgUuid'
import { Route as AdminOrderUuidRouteImport } from './routes/admin/order/$uuid'
import { Route as AdminInstructorWithdrawalsRouteImport } from './routes/admin/instructor/withdrawals'
import { Route as AdminInstructorRevenueRouteImport } from './routes/admin/instructor/revenue'
import { Route as AdminInstructorBankAccountsRouteImport } from './routes/admin/instructor/bank-accounts'
import { Route as AdminInstructorApplicationsUuidRouteImport } from './routes/admin/instructor-applications/$uuid'
import { Route as AdminFinanceWithdrawalsRouteImport } from './routes/admin/finance/withdrawals'
import { Route as AdminFinanceRevenueRouteImport } from './routes/admin/finance/revenue'
import { Route as AdminFinancePlatformFeesRouteImport } from './routes/admin/finance/platform-fees'
import { Route as AdminFinancePayoutsRouteImport } from './routes/admin/finance/payouts'
import { Route as AdminFinanceFeeConfigRouteImport } from './routes/admin/finance/fee-config'
import { Route as AdminCourseEnrollmentRouteImport } from './routes/admin/course/enrollment'
import { Route as AdminCourseCategoryRouteImport } from './routes/admin/course/category'
import { Route as AdminCourseCourseIdRouteImport } from './routes/admin/course/$courseId'
import { Route as AdminArticleCreateRouteImport } from './routes/admin/article/create'
import { Route as AdminArticleCategoryRouteImport } from './routes/admin/article/category'
import { Route as AdminArticleArticleIdRouteImport } from './routes/admin/article/$articleId'
import { Route as AdminGuideWithdrawalIndexRouteImport } from './routes/admin/guide/withdrawal/index'
import { Route as AdminGuidePromotionIndexRouteImport } from './routes/admin/guide/promotion/index'
import { Route as AdminGuideFeaturedCourseIndexRouteImport } from './routes/admin/guide/featured-course/index'
import { Route as AdminGuideCourseIndexRouteImport } from './routes/admin/guide/course/index'
import { Route as AdminPromotionPromotionIdEditRouteImport } from './routes/admin/promotion/$promotionId.edit'
import { Route as AdminCourseGradebookCourseIdRouteImport } from './routes/admin/course/gradebook.$courseId'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const TentangKamiRoute = TentangKamiRouteImport.update({
  id: '/tentang-kami',
  path: '/tentang-kami',
  getParentRoute: () => rootRouteImport,
} as any)
const SyaratKetentuanRoute = SyaratKetentuanRouteImport.update({
  id: '/syarat-ketentuan',
  path: '/syarat-ketentuan',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchOldRoute = SearchOldRouteImport.update({
  id: '/search-old',
  path: '/search-old',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginNewRoute = LoginNewRouteImport.update({
  id: '/login-new',
  path: '/login-new',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KebijakanPrivasiRoute = KebijakanPrivasiRouteImport.update({
  id: '/kebijakan-privasi',
  path: '/kebijakan-privasi',
  getParentRoute: () => rootRouteImport,
} as any)
const HubungiKamiRoute = HubungiKamiRouteImport.update({
  id: '/hubungi-kami',
  path: '/hubungi-kami',
  getParentRoute: () => rootRouteImport,
} as any)
const DevRoute = DevRouteImport.update({
  id: '/dev',
  path: '/dev',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugAuthRoute = DebugAuthRouteImport.update({
  id: '/debug-auth',
  path: '/debug-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientRoute = ClientRouteImport.update({
  id: '/client',
  path: '/client',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const BecomeAnInstructorRoute = BecomeAnInstructorRouteImport.update({
  id: '/become-an-instructor',
  path: '/become-an-instructor',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticleRoute = ArticleRouteImport.update({
  id: '/article',
  path: '/article',
  getParentRoute: () => rootRouteImport,
} as any)
const AksesibilitasRoute = AksesibilitasRouteImport.update({
  id: '/aksesibilitas',
  path: '/aksesibilitas',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const VerifyUuidRoute = VerifyUuidRouteImport.update({
  id: '/verify/$uuid',
  path: '/verify/$uuid',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentWishlistRoute = StudentWishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => StudentRoute,
} as any)
const StudentSettingsRoute = StudentSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => StudentRoute,
} as any)
const StudentProfileRoute = StudentProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => StudentRoute,
} as any)
const StudentNotificationSettingsRoute =
  StudentNotificationSettingsRouteImport.update({
    id: '/notification-settings',
    path: '/notification-settings',
    getParentRoute: () => StudentRoute,
  } as any)
const StudentNotificationRoute = StudentNotificationRouteImport.update({
  id: '/notification',
  path: '/notification',
  getParentRoute: () => StudentRoute,
} as any)
const StudentDashboardRoute = StudentDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => StudentRoute,
} as any)
const CourseCourseSlugRoute = CourseCourseSlugRouteImport.update({
  id: '/course/$courseSlug',
  path: '/course/$courseSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesSlugRoute = CategoriesSlugRouteImport.update({
  id: '/categories/$slug',
  path: '/categories/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationRoute = AdminNotificationRouteImport.update({
  id: '/notification',
  path: '/notification',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGalleryRoute = AdminGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFeaturedCoursesRoute = AdminFeaturedCoursesRouteImport.update({
  id: '/featured-courses',
  path: '/featured-courses',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBannersRoute = AdminBannersRouteImport.update({
  id: '/banners',
  path: '/banners',
  getParentRoute: () => AdminRoute,
} as any)
const StudentOrderIndexRoute = StudentOrderIndexRouteImport.update({
  id: '/order/',
  path: '/order/',
  getParentRoute: () => StudentRoute,
} as any)
const InstructorApplyIndexRoute = InstructorApplyIndexRouteImport.update({
  id: '/instructor/apply/',
  path: '/instructor/apply/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUserIndexRoute = AdminUserIndexRouteImport.update({
  id: '/user/',
  path: '/user/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRoleIndexRoute = AdminRoleIndexRouteImport.update({
  id: '/role/',
  path: '/role/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminQuizIndexRoute = AdminQuizIndexRouteImport.update({
  id: '/quiz/',
  path: '/quiz/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPromotionIndexRoute = AdminPromotionIndexRouteImport.update({
  id: '/promotion/',
  path: '/promotion/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrganizationIndexRoute = AdminOrganizationIndexRouteImport.update({
  id: '/organization/',
  path: '/organization/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrderIndexRoute = AdminOrderIndexRouteImport.update({
  id: '/order/',
  path: '/order/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInstructorApplicationsIndexRoute =
  AdminInstructorApplicationsIndexRouteImport.update({
    id: '/instructor-applications/',
    path: '/instructor-applications/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminGuideIndexRoute = AdminGuideIndexRouteImport.update({
  id: '/guide/',
  path: '/guide/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCourseIndexRoute = AdminCourseIndexRouteImport.update({
  id: '/course/',
  path: '/course/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminArticleIndexRoute = AdminArticleIndexRouteImport.update({
  id: '/article/',
  path: '/article/',
  getParentRoute: () => AdminRoute,
} as any)
const StudentOrderUuidRoute = StudentOrderUuidRouteImport.update({
  id: '/order/$uuid',
  path: '/order/$uuid',
  getParentRoute: () => StudentRoute,
} as any)
const StudentLearnCourseUuidRoute = StudentLearnCourseUuidRouteImport.update({
  id: '/learn/$courseUuid',
  path: '/learn/$courseUuid',
  getParentRoute: () => StudentRoute,
} as any)
const InstructorApplyStatusRoute = InstructorApplyStatusRouteImport.update({
  id: '/instructor/apply/status',
  path: '/instructor/apply/status',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificateVerifyPreviewRoute =
  CertificateVerifyPreviewRouteImport.update({
    id: '/certificate/verify/preview',
    path: '/certificate/verify/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const CertificateVerifyUuidRoute = CertificateVerifyUuidRouteImport.update({
  id: '/certificate/verify/$uuid',
  path: '/certificate/verify/$uuid',
  getParentRoute: () => rootRouteImport,
} as any)
const B2bActivateInvitationUuidRoute =
  B2bActivateInvitationUuidRouteImport.update({
    id: '/b2b/activate/$invitationUuid',
    path: '/b2b/activate/$invitationUuid',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminSettingPlatformRoute = AdminSettingPlatformRouteImport.update({
  id: '/setting/platform',
  path: '/setting/platform',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingPaymentMethodRoute =
  AdminSettingPaymentMethodRouteImport.update({
    id: '/setting/payment-method',
    path: '/setting/payment-method',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminSettingNotificationPreferencesRoute =
  AdminSettingNotificationPreferencesRouteImport.update({
    id: '/setting/notification-preferences',
    path: '/setting/notification-preferences',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminSettingAppRoute = AdminSettingAppRouteImport.update({
  id: '/setting/app',
  path: '/setting/app',
  getParentRoute: () => AdminRoute,
} as any)
const AdminQuizQuizUuidRoute = AdminQuizQuizUuidRouteImport.update({
  id: '/quiz/$quizUuid',
  path: '/quiz/$quizUuid',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPromotionCreateVoucherRoute =
  AdminPromotionCreateVoucherRouteImport.update({
    id: '/promotion/create-voucher',
    path: '/promotion/create-voucher',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminPromotionCreateRoute = AdminPromotionCreateRouteImport.update({
  id: '/promotion/create',
  path: '/promotion/create',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPromotionCouponRoute = AdminPromotionCouponRouteImport.update({
  id: '/promotion/coupon',
  path: '/promotion/coupon',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrganizationTagRoute = AdminOrganizationTagRouteImport.update({
  id: '/organization/tag',
  path: '/organization/tag',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrganizationOrgUuidRoute =
  AdminOrganizationOrgUuidRouteImport.update({
    id: '/organization/$orgUuid',
    path: '/organization/$orgUuid',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminOrderUuidRoute = AdminOrderUuidRouteImport.update({
  id: '/order/$uuid',
  path: '/order/$uuid',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInstructorWithdrawalsRoute =
  AdminInstructorWithdrawalsRouteImport.update({
    id: '/instructor/withdrawals',
    path: '/instructor/withdrawals',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminInstructorRevenueRoute = AdminInstructorRevenueRouteImport.update({
  id: '/instructor/revenue',
  path: '/instructor/revenue',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInstructorBankAccountsRoute =
  AdminInstructorBankAccountsRouteImport.update({
    id: '/instructor/bank-accounts',
    path: '/instructor/bank-accounts',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminInstructorApplicationsUuidRoute =
  AdminInstructorApplicationsUuidRouteImport.update({
    id: '/instructor-applications/$uuid',
    path: '/instructor-applications/$uuid',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminFinanceWithdrawalsRoute = AdminFinanceWithdrawalsRouteImport.update({
  id: '/finance/withdrawals',
  path: '/finance/withdrawals',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinanceRevenueRoute = AdminFinanceRevenueRouteImport.update({
  id: '/finance/revenue',
  path: '/finance/revenue',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinancePlatformFeesRoute =
  AdminFinancePlatformFeesRouteImport.update({
    id: '/finance/platform-fees',
    path: '/finance/platform-fees',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminFinancePayoutsRoute = AdminFinancePayoutsRouteImport.update({
  id: '/finance/payouts',
  path: '/finance/payouts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinanceFeeConfigRoute = AdminFinanceFeeConfigRouteImport.update({
  id: '/finance/fee-config',
  path: '/finance/fee-config',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCourseEnrollmentRoute = AdminCourseEnrollmentRouteImport.update({
  id: '/course/enrollment',
  path: '/course/enrollment',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCourseCategoryRoute = AdminCourseCategoryRouteImport.update({
  id: '/course/category',
  path: '/course/category',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCourseCourseIdRoute = AdminCourseCourseIdRouteImport.update({
  id: '/course/$courseId',
  path: '/course/$courseId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminArticleCreateRoute = AdminArticleCreateRouteImport.update({
  id: '/article/create',
  path: '/article/create',
  getParentRoute: () => AdminRoute,
} as any)
const AdminArticleCategoryRoute = AdminArticleCategoryRouteImport.update({
  id: '/article/category',
  path: '/article/category',
  getParentRoute: () => AdminRoute,
} as any)
const AdminArticleArticleIdRoute = AdminArticleArticleIdRouteImport.update({
  id: '/article/$articleId',
  path: '/article/$articleId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGuideWithdrawalIndexRoute =
  AdminGuideWithdrawalIndexRouteImport.update({
    id: '/guide/withdrawal/',
    path: '/guide/withdrawal/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminGuidePromotionIndexRoute =
  AdminGuidePromotionIndexRouteImport.update({
    id: '/guide/promotion/',
    path: '/guide/promotion/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminGuideFeaturedCourseIndexRoute =
  AdminGuideFeaturedCourseIndexRouteImport.update({
    id: '/guide/featured-course/',
    path: '/guide/featured-course/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminGuideCourseIndexRoute = AdminGuideCourseIndexRouteImport.update({
  id: '/guide/course/',
  path: '/guide/course/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPromotionPromotionIdEditRoute =
  AdminPromotionPromotionIdEditRouteImport.update({
    id: '/promotion/$promotionId/edit',
    path: '/promotion/$promotionId/edit',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminCourseGradebookCourseIdRoute =
  AdminCourseGradebookCourseIdRouteImport.update({
    id: '/course/gradebook/$courseId',
    path: '/course/gradebook/$courseId',
    getParentRoute: () => AdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/aksesibilitas': typeof AksesibilitasRoute
  '/article': typeof ArticleRoute
  '/become-an-instructor': typeof BecomeAnInstructorRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/client': typeof ClientRoute
  '/debug-auth': typeof DebugAuthRoute
  '/dev': typeof DevRoute
  '/hubungi-kami': typeof HubungiKamiRoute
  '/kebijakan-privasi': typeof KebijakanPrivasiRoute
  '/login': typeof LoginRoute
  '/login-new': typeof LoginNewRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/search-old': typeof SearchOldRoute
  '/student': typeof StudentRouteWithChildren
  '/syarat-ketentuan': typeof SyaratKetentuanRoute
  '/tentang-kami': typeof TentangKamiRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/featured-courses': typeof AdminFeaturedCoursesRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/notification': typeof AdminNotificationRoute
  '/admin/profile': typeof AdminProfileRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/course/$courseSlug': typeof CourseCourseSlugRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/notification': typeof StudentNotificationRoute
  '/student/notification-settings': typeof StudentNotificationSettingsRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/settings': typeof StudentSettingsRoute
  '/student/wishlist': typeof StudentWishlistRoute
  '/verify/$uuid': typeof VerifyUuidRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/article/$articleId': typeof AdminArticleArticleIdRoute
  '/admin/article/category': typeof AdminArticleCategoryRoute
  '/admin/article/create': typeof AdminArticleCreateRoute
  '/admin/course/$courseId': typeof AdminCourseCourseIdRoute
  '/admin/course/category': typeof AdminCourseCategoryRoute
  '/admin/course/enrollment': typeof AdminCourseEnrollmentRoute
  '/admin/finance/fee-config': typeof AdminFinanceFeeConfigRoute
  '/admin/finance/payouts': typeof AdminFinancePayoutsRoute
  '/admin/finance/platform-fees': typeof AdminFinancePlatformFeesRoute
  '/admin/finance/revenue': typeof AdminFinanceRevenueRoute
  '/admin/finance/withdrawals': typeof AdminFinanceWithdrawalsRoute
  '/admin/instructor-applications/$uuid': typeof AdminInstructorApplicationsUuidRoute
  '/admin/instructor/bank-accounts': typeof AdminInstructorBankAccountsRoute
  '/admin/instructor/revenue': typeof AdminInstructorRevenueRoute
  '/admin/instructor/withdrawals': typeof AdminInstructorWithdrawalsRoute
  '/admin/order/$uuid': typeof AdminOrderUuidRoute
  '/admin/organization/$orgUuid': typeof AdminOrganizationOrgUuidRoute
  '/admin/organization/tag': typeof AdminOrganizationTagRoute
  '/admin/promotion/coupon': typeof AdminPromotionCouponRoute
  '/admin/promotion/create': typeof AdminPromotionCreateRoute
  '/admin/promotion/create-voucher': typeof AdminPromotionCreateVoucherRoute
  '/admin/quiz/$quizUuid': typeof AdminQuizQuizUuidRoute
  '/admin/setting/app': typeof AdminSettingAppRoute
  '/admin/setting/notification-preferences': typeof AdminSettingNotificationPreferencesRoute
  '/admin/setting/payment-method': typeof AdminSettingPaymentMethodRoute
  '/admin/setting/platform': typeof AdminSettingPlatformRoute
  '/b2b/activate/$invitationUuid': typeof B2bActivateInvitationUuidRoute
  '/certificate/verify/$uuid': typeof CertificateVerifyUuidRoute
  '/certificate/verify/preview': typeof CertificateVerifyPreviewRoute
  '/instructor/apply/status': typeof InstructorApplyStatusRoute
  '/student/learn/$courseUuid': typeof StudentLearnCourseUuidRoute
  '/student/order/$uuid': typeof StudentOrderUuidRoute
  '/admin/article/': typeof AdminArticleIndexRoute
  '/admin/course/': typeof AdminCourseIndexRoute
  '/admin/guide/': typeof AdminGuideIndexRoute
  '/admin/instructor-applications/': typeof AdminInstructorApplicationsIndexRoute
  '/admin/order/': typeof AdminOrderIndexRoute
  '/admin/organization/': typeof AdminOrganizationIndexRoute
  '/admin/promotion/': typeof AdminPromotionIndexRoute
  '/admin/quiz/': typeof AdminQuizIndexRoute
  '/admin/role/': typeof AdminRoleIndexRoute
  '/admin/user/': typeof AdminUserIndexRoute
  '/instructor/apply/': typeof InstructorApplyIndexRoute
  '/student/order/': typeof StudentOrderIndexRoute
  '/admin/course/gradebook/$courseId': typeof AdminCourseGradebookCourseIdRoute
  '/admin/promotion/$promotionId/edit': typeof AdminPromotionPromotionIdEditRoute
  '/admin/guide/course/': typeof AdminGuideCourseIndexRoute
  '/admin/guide/featured-course/': typeof AdminGuideFeaturedCourseIndexRoute
  '/admin/guide/promotion/': typeof AdminGuidePromotionIndexRoute
  '/admin/guide/withdrawal/': typeof AdminGuideWithdrawalIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aksesibilitas': typeof AksesibilitasRoute
  '/article': typeof ArticleRoute
  '/become-an-instructor': typeof BecomeAnInstructorRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/client': typeof ClientRoute
  '/debug-auth': typeof DebugAuthRoute
  '/dev': typeof DevRoute
  '/hubungi-kami': typeof HubungiKamiRoute
  '/kebijakan-privasi': typeof KebijakanPrivasiRoute
  '/login': typeof LoginRoute
  '/login-new': typeof LoginNewRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/search-old': typeof SearchOldRoute
  '/student': typeof StudentRouteWithChildren
  '/syarat-ketentuan': typeof SyaratKetentuanRoute
  '/tentang-kami': typeof TentangKamiRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/featured-courses': typeof AdminFeaturedCoursesRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/notification': typeof AdminNotificationRoute
  '/admin/profile': typeof AdminProfileRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/course/$courseSlug': typeof CourseCourseSlugRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/notification': typeof StudentNotificationRoute
  '/student/notification-settings': typeof StudentNotificationSettingsRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/settings': typeof StudentSettingsRoute
  '/student/wishlist': typeof StudentWishlistRoute
  '/verify/$uuid': typeof VerifyUuidRoute
  '/admin': typeof AdminIndexRoute
  '/admin/article/$articleId': typeof AdminArticleArticleIdRoute
  '/admin/article/category': typeof AdminArticleCategoryRoute
  '/admin/article/create': typeof AdminArticleCreateRoute
  '/admin/course/$courseId': typeof AdminCourseCourseIdRoute
  '/admin/course/category': typeof AdminCourseCategoryRoute
  '/admin/course/enrollment': typeof AdminCourseEnrollmentRoute
  '/admin/finance/fee-config': typeof AdminFinanceFeeConfigRoute
  '/admin/finance/payouts': typeof AdminFinancePayoutsRoute
  '/admin/finance/platform-fees': typeof AdminFinancePlatformFeesRoute
  '/admin/finance/revenue': typeof AdminFinanceRevenueRoute
  '/admin/finance/withdrawals': typeof AdminFinanceWithdrawalsRoute
  '/admin/instructor-applications/$uuid': typeof AdminInstructorApplicationsUuidRoute
  '/admin/instructor/bank-accounts': typeof AdminInstructorBankAccountsRoute
  '/admin/instructor/revenue': typeof AdminInstructorRevenueRoute
  '/admin/instructor/withdrawals': typeof AdminInstructorWithdrawalsRoute
  '/admin/order/$uuid': typeof AdminOrderUuidRoute
  '/admin/organization/$orgUuid': typeof AdminOrganizationOrgUuidRoute
  '/admin/organization/tag': typeof AdminOrganizationTagRoute
  '/admin/promotion/coupon': typeof AdminPromotionCouponRoute
  '/admin/promotion/create': typeof AdminPromotionCreateRoute
  '/admin/promotion/create-voucher': typeof AdminPromotionCreateVoucherRoute
  '/admin/quiz/$quizUuid': typeof AdminQuizQuizUuidRoute
  '/admin/setting/app': typeof AdminSettingAppRoute
  '/admin/setting/notification-preferences': typeof AdminSettingNotificationPreferencesRoute
  '/admin/setting/payment-method': typeof AdminSettingPaymentMethodRoute
  '/admin/setting/platform': typeof AdminSettingPlatformRoute
  '/b2b/activate/$invitationUuid': typeof B2bActivateInvitationUuidRoute
  '/certificate/verify/$uuid': typeof CertificateVerifyUuidRoute
  '/certificate/verify/preview': typeof CertificateVerifyPreviewRoute
  '/instructor/apply/status': typeof InstructorApplyStatusRoute
  '/student/learn/$courseUuid': typeof StudentLearnCourseUuidRoute
  '/student/order/$uuid': typeof StudentOrderUuidRoute
  '/admin/article': typeof AdminArticleIndexRoute
  '/admin/course': typeof AdminCourseIndexRoute
  '/admin/guide': typeof AdminGuideIndexRoute
  '/admin/instructor-applications': typeof AdminInstructorApplicationsIndexRoute
  '/admin/order': typeof AdminOrderIndexRoute
  '/admin/organization': typeof AdminOrganizationIndexRoute
  '/admin/promotion': typeof AdminPromotionIndexRoute
  '/admin/quiz': typeof AdminQuizIndexRoute
  '/admin/role': typeof AdminRoleIndexRoute
  '/admin/user': typeof AdminUserIndexRoute
  '/instructor/apply': typeof InstructorApplyIndexRoute
  '/student/order': typeof StudentOrderIndexRoute
  '/admin/course/gradebook/$courseId': typeof AdminCourseGradebookCourseIdRoute
  '/admin/promotion/$promotionId/edit': typeof AdminPromotionPromotionIdEditRoute
  '/admin/guide/course': typeof AdminGuideCourseIndexRoute
  '/admin/guide/featured-course': typeof AdminGuideFeaturedCourseIndexRoute
  '/admin/guide/promotion': typeof AdminGuidePromotionIndexRoute
  '/admin/guide/withdrawal': typeof AdminGuideWithdrawalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/aksesibilitas': typeof AksesibilitasRoute
  '/article': typeof ArticleRoute
  '/become-an-instructor': typeof BecomeAnInstructorRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/client': typeof ClientRoute
  '/debug-auth': typeof DebugAuthRoute
  '/dev': typeof DevRoute
  '/hubungi-kami': typeof HubungiKamiRoute
  '/kebijakan-privasi': typeof KebijakanPrivasiRoute
  '/login': typeof LoginRoute
  '/login-new': typeof LoginNewRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/search-old': typeof SearchOldRoute
  '/student': typeof StudentRouteWithChildren
  '/syarat-ketentuan': typeof SyaratKetentuanRoute
  '/tentang-kami': typeof TentangKamiRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/featured-courses': typeof AdminFeaturedCoursesRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/notification': typeof AdminNotificationRoute
  '/admin/profile': typeof AdminProfileRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/course/$courseSlug': typeof CourseCourseSlugRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/notification': typeof StudentNotificationRoute
  '/student/notification-settings': typeof StudentNotificationSettingsRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/settings': typeof StudentSettingsRoute
  '/student/wishlist': typeof StudentWishlistRoute
  '/verify/$uuid': typeof VerifyUuidRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/article/$articleId': typeof AdminArticleArticleIdRoute
  '/admin/article/category': typeof AdminArticleCategoryRoute
  '/admin/article/create': typeof AdminArticleCreateRoute
  '/admin/course/$courseId': typeof AdminCourseCourseIdRoute
  '/admin/course/category': typeof AdminCourseCategoryRoute
  '/admin/course/enrollment': typeof AdminCourseEnrollmentRoute
  '/admin/finance/fee-config': typeof AdminFinanceFeeConfigRoute
  '/admin/finance/payouts': typeof AdminFinancePayoutsRoute
  '/admin/finance/platform-fees': typeof AdminFinancePlatformFeesRoute
  '/admin/finance/revenue': typeof AdminFinanceRevenueRoute
  '/admin/finance/withdrawals': typeof AdminFinanceWithdrawalsRoute
  '/admin/instructor-applications/$uuid': typeof AdminInstructorApplicationsUuidRoute
  '/admin/instructor/bank-accounts': typeof AdminInstructorBankAccountsRoute
  '/admin/instructor/revenue': typeof AdminInstructorRevenueRoute
  '/admin/instructor/withdrawals': typeof AdminInstructorWithdrawalsRoute
  '/admin/order/$uuid': typeof AdminOrderUuidRoute
  '/admin/organization/$orgUuid': typeof AdminOrganizationOrgUuidRoute
  '/admin/organization/tag': typeof AdminOrganizationTagRoute
  '/admin/promotion/coupon': typeof AdminPromotionCouponRoute
  '/admin/promotion/create': typeof AdminPromotionCreateRoute
  '/admin/promotion/create-voucher': typeof AdminPromotionCreateVoucherRoute
  '/admin/quiz/$quizUuid': typeof AdminQuizQuizUuidRoute
  '/admin/setting/app': typeof AdminSettingAppRoute
  '/admin/setting/notification-preferences': typeof AdminSettingNotificationPreferencesRoute
  '/admin/setting/payment-method': typeof AdminSettingPaymentMethodRoute
  '/admin/setting/platform': typeof AdminSettingPlatformRoute
  '/b2b/activate/$invitationUuid': typeof B2bActivateInvitationUuidRoute
  '/certificate/verify/$uuid': typeof CertificateVerifyUuidRoute
  '/certificate/verify/preview': typeof CertificateVerifyPreviewRoute
  '/instructor/apply/status': typeof InstructorApplyStatusRoute
  '/student/learn/$courseUuid': typeof StudentLearnCourseUuidRoute
  '/student/order/$uuid': typeof StudentOrderUuidRoute
  '/admin/article/': typeof AdminArticleIndexRoute
  '/admin/course/': typeof AdminCourseIndexRoute
  '/admin/guide/': typeof AdminGuideIndexRoute
  '/admin/instructor-applications/': typeof AdminInstructorApplicationsIndexRoute
  '/admin/order/': typeof AdminOrderIndexRoute
  '/admin/organization/': typeof AdminOrganizationIndexRoute
  '/admin/promotion/': typeof AdminPromotionIndexRoute
  '/admin/quiz/': typeof AdminQuizIndexRoute
  '/admin/role/': typeof AdminRoleIndexRoute
  '/admin/user/': typeof AdminUserIndexRoute
  '/instructor/apply/': typeof InstructorApplyIndexRoute
  '/student/order/': typeof StudentOrderIndexRoute
  '/admin/course/gradebook/$courseId': typeof AdminCourseGradebookCourseIdRoute
  '/admin/promotion/$promotionId/edit': typeof AdminPromotionPromotionIdEditRoute
  '/admin/guide/course/': typeof AdminGuideCourseIndexRoute
  '/admin/guide/featured-course/': typeof AdminGuideFeaturedCourseIndexRoute
  '/admin/guide/promotion/': typeof AdminGuidePromotionIndexRoute
  '/admin/guide/withdrawal/': typeof AdminGuideWithdrawalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/aksesibilitas'
    | '/article'
    | '/become-an-instructor'
    | '/cart'
    | '/checkout'
    | '/client'
    | '/debug-auth'
    | '/dev'
    | '/hubungi-kami'
    | '/kebijakan-privasi'
    | '/login'
    | '/login-new'
    | '/register'
    | '/search'
    | '/search-old'
    | '/student'
    | '/syarat-ketentuan'
    | '/tentang-kami'
    | '/verify-email'
    | '/admin/banners'
    | '/admin/dashboard'
    | '/admin/featured-courses'
    | '/admin/gallery'
    | '/admin/notification'
    | '/admin/profile'
    | '/auth/callback'
    | '/categories/$slug'
    | '/course/$courseSlug'
    | '/student/dashboard'
    | '/student/notification'
    | '/student/notification-settings'
    | '/student/profile'
    | '/student/settings'
    | '/student/wishlist'
    | '/verify/$uuid'
    | '/admin/'
    | '/admin/article/$articleId'
    | '/admin/article/category'
    | '/admin/article/create'
    | '/admin/course/$courseId'
    | '/admin/course/category'
    | '/admin/course/enrollment'
    | '/admin/finance/fee-config'
    | '/admin/finance/payouts'
    | '/admin/finance/platform-fees'
    | '/admin/finance/revenue'
    | '/admin/finance/withdrawals'
    | '/admin/instructor-applications/$uuid'
    | '/admin/instructor/bank-accounts'
    | '/admin/instructor/revenue'
    | '/admin/instructor/withdrawals'
    | '/admin/order/$uuid'
    | '/admin/organization/$orgUuid'
    | '/admin/organization/tag'
    | '/admin/promotion/coupon'
    | '/admin/promotion/create'
    | '/admin/promotion/create-voucher'
    | '/admin/quiz/$quizUuid'
    | '/admin/setting/app'
    | '/admin/setting/notification-preferences'
    | '/admin/setting/payment-method'
    | '/admin/setting/platform'
    | '/b2b/activate/$invitationUuid'
    | '/certificate/verify/$uuid'
    | '/certificate/verify/preview'
    | '/instructor/apply/status'
    | '/student/learn/$courseUuid'
    | '/student/order/$uuid'
    | '/admin/article/'
    | '/admin/course/'
    | '/admin/guide/'
    | '/admin/instructor-applications/'
    | '/admin/order/'
    | '/admin/organization/'
    | '/admin/promotion/'
    | '/admin/quiz/'
    | '/admin/role/'
    | '/admin/user/'
    | '/instructor/apply/'
    | '/student/order/'
    | '/admin/course/gradebook/$courseId'
    | '/admin/promotion/$promotionId/edit'
    | '/admin/guide/course/'
    | '/admin/guide/featured-course/'
    | '/admin/guide/promotion/'
    | '/admin/guide/withdrawal/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aksesibilitas'
    | '/article'
    | '/become-an-instructor'
    | '/cart'
    | '/checkout'
    | '/client'
    | '/debug-auth'
    | '/dev'
    | '/hubungi-kami'
    | '/kebijakan-privasi'
    | '/login'
    | '/login-new'
    | '/register'
    | '/search'
    | '/search-old'
    | '/student'
    | '/syarat-ketentuan'
    | '/tentang-kami'
    | '/verify-email'
    | '/admin/banners'
    | '/admin/dashboard'
    | '/admin/featured-courses'
    | '/admin/gallery'
    | '/admin/notification'
    | '/admin/profile'
    | '/auth/callback'
    | '/categories/$slug'
    | '/course/$courseSlug'
    | '/student/dashboard'
    | '/student/notification'
    | '/student/notification-settings'
    | '/student/profile'
    | '/student/settings'
    | '/student/wishlist'
    | '/verify/$uuid'
    | '/admin'
    | '/admin/article/$articleId'
    | '/admin/article/category'
    | '/admin/article/create'
    | '/admin/course/$courseId'
    | '/admin/course/category'
    | '/admin/course/enrollment'
    | '/admin/finance/fee-config'
    | '/admin/finance/payouts'
    | '/admin/finance/platform-fees'
    | '/admin/finance/revenue'
    | '/admin/finance/withdrawals'
    | '/admin/instructor-applications/$uuid'
    | '/admin/instructor/bank-accounts'
    | '/admin/instructor/revenue'
    | '/admin/instructor/withdrawals'
    | '/admin/order/$uuid'
    | '/admin/organization/$orgUuid'
    | '/admin/organization/tag'
    | '/admin/promotion/coupon'
    | '/admin/promotion/create'
    | '/admin/promotion/create-voucher'
    | '/admin/quiz/$quizUuid'
    | '/admin/setting/app'
    | '/admin/setting/notification-preferences'
    | '/admin/setting/payment-method'
    | '/admin/setting/platform'
    | '/b2b/activate/$invitationUuid'
    | '/certificate/verify/$uuid'
    | '/certificate/verify/preview'
    | '/instructor/apply/status'
    | '/student/learn/$courseUuid'
    | '/student/order/$uuid'
    | '/admin/article'
    | '/admin/course'
    | '/admin/guide'
    | '/admin/instructor-applications'
    | '/admin/order'
    | '/admin/organization'
    | '/admin/promotion'
    | '/admin/quiz'
    | '/admin/role'
    | '/admin/user'
    | '/instructor/apply'
    | '/student/order'
    | '/admin/course/gradebook/$courseId'
    | '/admin/promotion/$promotionId/edit'
    | '/admin/guide/course'
    | '/admin/guide/featured-course'
    | '/admin/guide/promotion'
    | '/admin/guide/withdrawal'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/aksesibilitas'
    | '/article'
    | '/become-an-instructor'
    | '/cart'
    | '/checkout'
    | '/client'
    | '/debug-auth'
    | '/dev'
    | '/hubungi-kami'
    | '/kebijakan-privasi'
    | '/login'
    | '/login-new'
    | '/register'
    | '/search'
    | '/search-old'
    | '/student'
    | '/syarat-ketentuan'
    | '/tentang-kami'
    | '/verify-email'
    | '/admin/banners'
    | '/admin/dashboard'
    | '/admin/featured-courses'
    | '/admin/gallery'
    | '/admin/notification'
    | '/admin/profile'
    | '/auth/callback'
    | '/categories/$slug'
    | '/course/$courseSlug'
    | '/student/dashboard'
    | '/student/notification'
    | '/student/notification-settings'
    | '/student/profile'
    | '/student/settings'
    | '/student/wishlist'
    | '/verify/$uuid'
    | '/admin/'
    | '/admin/article/$articleId'
    | '/admin/article/category'
    | '/admin/article/create'
    | '/admin/course/$courseId'
    | '/admin/course/category'
    | '/admin/course/enrollment'
    | '/admin/finance/fee-config'
    | '/admin/finance/payouts'
    | '/admin/finance/platform-fees'
    | '/admin/finance/revenue'
    | '/admin/finance/withdrawals'
    | '/admin/instructor-applications/$uuid'
    | '/admin/instructor/bank-accounts'
    | '/admin/instructor/revenue'
    | '/admin/instructor/withdrawals'
    | '/admin/order/$uuid'
    | '/admin/organization/$orgUuid'
    | '/admin/organization/tag'
    | '/admin/promotion/coupon'
    | '/admin/promotion/create'
    | '/admin/promotion/create-voucher'
    | '/admin/quiz/$quizUuid'
    | '/admin/setting/app'
    | '/admin/setting/notification-preferences'
    | '/admin/setting/payment-method'
    | '/admin/setting/platform'
    | '/b2b/activate/$invitationUuid'
    | '/certificate/verify/$uuid'
    | '/certificate/verify/preview'
    | '/instructor/apply/status'
    | '/student/learn/$courseUuid'
    | '/student/order/$uuid'
    | '/admin/article/'
    | '/admin/course/'
    | '/admin/guide/'
    | '/admin/instructor-applications/'
    | '/admin/order/'
    | '/admin/organization/'
    | '/admin/promotion/'
    | '/admin/quiz/'
    | '/admin/role/'
    | '/admin/user/'
    | '/instructor/apply/'
    | '/student/order/'
    | '/admin/course/gradebook/$courseId'
    | '/admin/promotion/$promotionId/edit'
    | '/admin/guide/course/'
    | '/admin/guide/featured-course/'
    | '/admin/guide/promotion/'
    | '/admin/guide/withdrawal/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AksesibilitasRoute: typeof AksesibilitasRoute
  ArticleRoute: typeof ArticleRoute
  BecomeAnInstructorRoute: typeof BecomeAnInstructorRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ClientRoute: typeof ClientRoute
  DebugAuthRoute: typeof DebugAuthRoute
  DevRoute: typeof DevRoute
  HubungiKamiRoute: typeof HubungiKamiRoute
  KebijakanPrivasiRoute: typeof KebijakanPrivasiRoute
  LoginRoute: typeof LoginRoute
  LoginNewRoute: typeof LoginNewRoute
  RegisterRoute: typeof RegisterRoute
  SearchRoute: typeof SearchRoute
  SearchOldRoute: typeof SearchOldRoute
  StudentRoute: typeof StudentRouteWithChildren
  SyaratKetentuanRoute: typeof SyaratKetentuanRoute
  TentangKamiRoute: typeof TentangKamiRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  CategoriesSlugRoute: typeof CategoriesSlugRoute
  CourseCourseSlugRoute: typeof CourseCourseSlugRoute
  VerifyUuidRoute: typeof VerifyUuidRoute
  B2bActivateInvitationUuidRoute: typeof B2bActivateInvitationUuidRoute
  CertificateVerifyUuidRoute: typeof CertificateVerifyUuidRoute
  CertificateVerifyPreviewRoute: typeof CertificateVerifyPreviewRoute
  InstructorApplyStatusRoute: typeof InstructorApplyStatusRoute
  InstructorApplyIndexRoute: typeof InstructorApplyIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tentang-kami': {
      id: '/tentang-kami'
      path: '/tentang-kami'
      fullPath: '/tentang-kami'
      preLoaderRoute: typeof TentangKamiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/syarat-ketentuan': {
      id: '/syarat-ketentuan'
      path: '/syarat-ketentuan'
      fullPath: '/syarat-ketentuan'
      preLoaderRoute: typeof SyaratKetentuanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search-old': {
      id: '/search-old'
      path: '/search-old'
      fullPath: '/search-old'
      preLoaderRoute: typeof SearchOldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login-new': {
      id: '/login-new'
      path: '/login-new'
      fullPath: '/login-new'
      preLoaderRoute: typeof LoginNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kebijakan-privasi': {
      id: '/kebijakan-privasi'
      path: '/kebijakan-privasi'
      fullPath: '/kebijakan-privasi'
      preLoaderRoute: typeof KebijakanPrivasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hubungi-kami': {
      id: '/hubungi-kami'
      path: '/hubungi-kami'
      fullPath: '/hubungi-kami'
      preLoaderRoute: typeof HubungiKamiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev': {
      id: '/dev'
      path: '/dev'
      fullPath: '/dev'
      preLoaderRoute: typeof DevRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug-auth': {
      id: '/debug-auth'
      path: '/debug-auth'
      fullPath: '/debug-auth'
      preLoaderRoute: typeof DebugAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client': {
      id: '/client'
      path: '/client'
      fullPath: '/client'
      preLoaderRoute: typeof ClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/become-an-instructor': {
      id: '/become-an-instructor'
      path: '/become-an-instructor'
      fullPath: '/become-an-instructor'
      preLoaderRoute: typeof BecomeAnInstructorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/article': {
      id: '/article'
      path: '/article'
      fullPath: '/article'
      preLoaderRoute: typeof ArticleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aksesibilitas': {
      id: '/aksesibilitas'
      path: '/aksesibilitas'
      fullPath: '/aksesibilitas'
      preLoaderRoute: typeof AksesibilitasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/verify/$uuid': {
      id: '/verify/$uuid'
      path: '/verify/$uuid'
      fullPath: '/verify/$uuid'
      preLoaderRoute: typeof VerifyUuidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/wishlist': {
      id: '/student/wishlist'
      path: '/wishlist'
      fullPath: '/student/wishlist'
      preLoaderRoute: typeof StudentWishlistRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/settings': {
      id: '/student/settings'
      path: '/settings'
      fullPath: '/student/settings'
      preLoaderRoute: typeof StudentSettingsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/profile': {
      id: '/student/profile'
      path: '/profile'
      fullPath: '/student/profile'
      preLoaderRoute: typeof StudentProfileRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/notification-settings': {
      id: '/student/notification-settings'
      path: '/notification-settings'
      fullPath: '/student/notification-settings'
      preLoaderRoute: typeof StudentNotificationSettingsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/notification': {
      id: '/student/notification'
      path: '/notification'
      fullPath: '/student/notification'
      preLoaderRoute: typeof StudentNotificationRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/dashboard': {
      id: '/student/dashboard'
      path: '/dashboard'
      fullPath: '/student/dashboard'
      preLoaderRoute: typeof StudentDashboardRouteImport
      parentRoute: typeof StudentRoute
    }
    '/course/$courseSlug': {
      id: '/course/$courseSlug'
      path: '/course/$courseSlug'
      fullPath: '/course/$courseSlug'
      preLoaderRoute: typeof CourseCourseSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/$slug': {
      id: '/categories/$slug'
      path: '/categories/$slug'
      fullPath: '/categories/$slug'
      preLoaderRoute: typeof CategoriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notification': {
      id: '/admin/notification'
      path: '/notification'
      fullPath: '/admin/notification'
      preLoaderRoute: typeof AdminNotificationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/gallery': {
      id: '/admin/gallery'
      path: '/gallery'
      fullPath: '/admin/gallery'
      preLoaderRoute: typeof AdminGalleryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/featured-courses': {
      id: '/admin/featured-courses'
      path: '/featured-courses'
      fullPath: '/admin/featured-courses'
      preLoaderRoute: typeof AdminFeaturedCoursesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/banners': {
      id: '/admin/banners'
      path: '/banners'
      fullPath: '/admin/banners'
      preLoaderRoute: typeof AdminBannersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/student/order/': {
      id: '/student/order/'
      path: '/order'
      fullPath: '/student/order/'
      preLoaderRoute: typeof StudentOrderIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/instructor/apply/': {
      id: '/instructor/apply/'
      path: '/instructor/apply'
      fullPath: '/instructor/apply/'
      preLoaderRoute: typeof InstructorApplyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/user/': {
      id: '/admin/user/'
      path: '/user'
      fullPath: '/admin/user/'
      preLoaderRoute: typeof AdminUserIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/role/': {
      id: '/admin/role/'
      path: '/role'
      fullPath: '/admin/role/'
      preLoaderRoute: typeof AdminRoleIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/quiz/': {
      id: '/admin/quiz/'
      path: '/quiz'
      fullPath: '/admin/quiz/'
      preLoaderRoute: typeof AdminQuizIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/promotion/': {
      id: '/admin/promotion/'
      path: '/promotion'
      fullPath: '/admin/promotion/'
      preLoaderRoute: typeof AdminPromotionIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/organization/': {
      id: '/admin/organization/'
      path: '/organization'
      fullPath: '/admin/organization/'
      preLoaderRoute: typeof AdminOrganizationIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/order/': {
      id: '/admin/order/'
      path: '/order'
      fullPath: '/admin/order/'
      preLoaderRoute: typeof AdminOrderIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/instructor-applications/': {
      id: '/admin/instructor-applications/'
      path: '/instructor-applications'
      fullPath: '/admin/instructor-applications/'
      preLoaderRoute: typeof AdminInstructorApplicationsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/guide/': {
      id: '/admin/guide/'
      path: '/guide'
      fullPath: '/admin/guide/'
      preLoaderRoute: typeof AdminGuideIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/course/': {
      id: '/admin/course/'
      path: '/course'
      fullPath: '/admin/course/'
      preLoaderRoute: typeof AdminCourseIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/article/': {
      id: '/admin/article/'
      path: '/article'
      fullPath: '/admin/article/'
      preLoaderRoute: typeof AdminArticleIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/student/order/$uuid': {
      id: '/student/order/$uuid'
      path: '/order/$uuid'
      fullPath: '/student/order/$uuid'
      preLoaderRoute: typeof StudentOrderUuidRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/learn/$courseUuid': {
      id: '/student/learn/$courseUuid'
      path: '/learn/$courseUuid'
      fullPath: '/student/learn/$courseUuid'
      preLoaderRoute: typeof StudentLearnCourseUuidRouteImport
      parentRoute: typeof StudentRoute
    }
    '/instructor/apply/status': {
      id: '/instructor/apply/status'
      path: '/instructor/apply/status'
      fullPath: '/instructor/apply/status'
      preLoaderRoute: typeof InstructorApplyStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificate/verify/preview': {
      id: '/certificate/verify/preview'
      path: '/certificate/verify/preview'
      fullPath: '/certificate/verify/preview'
      preLoaderRoute: typeof CertificateVerifyPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificate/verify/$uuid': {
      id: '/certificate/verify/$uuid'
      path: '/certificate/verify/$uuid'
      fullPath: '/certificate/verify/$uuid'
      preLoaderRoute: typeof CertificateVerifyUuidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/b2b/activate/$invitationUuid': {
      id: '/b2b/activate/$invitationUuid'
      path: '/b2b/activate/$invitationUuid'
      fullPath: '/b2b/activate/$invitationUuid'
      preLoaderRoute: typeof B2bActivateInvitationUuidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/setting/platform': {
      id: '/admin/setting/platform'
      path: '/setting/platform'
      fullPath: '/admin/setting/platform'
      preLoaderRoute: typeof AdminSettingPlatformRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/setting/payment-method': {
      id: '/admin/setting/payment-method'
      path: '/setting/payment-method'
      fullPath: '/admin/setting/payment-method'
      preLoaderRoute: typeof AdminSettingPaymentMethodRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/setting/notification-preferences': {
      id: '/admin/setting/notification-preferences'
      path: '/setting/notification-preferences'
      fullPath: '/admin/setting/notification-preferences'
      preLoaderRoute: typeof AdminSettingNotificationPreferencesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/setting/app': {
      id: '/admin/setting/app'
      path: '/setting/app'
      fullPath: '/admin/setting/app'
      preLoaderRoute: typeof AdminSettingAppRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/quiz/$quizUuid': {
      id: '/admin/quiz/$quizUuid'
      path: '/quiz/$quizUuid'
      fullPath: '/admin/quiz/$quizUuid'
      preLoaderRoute: typeof AdminQuizQuizUuidRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/promotion/create-voucher': {
      id: '/admin/promotion/create-voucher'
      path: '/promotion/create-voucher'
      fullPath: '/admin/promotion/create-voucher'
      preLoaderRoute: typeof AdminPromotionCreateVoucherRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/promotion/create': {
      id: '/admin/promotion/create'
      path: '/promotion/create'
      fullPath: '/admin/promotion/create'
      preLoaderRoute: typeof AdminPromotionCreateRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/promotion/coupon': {
      id: '/admin/promotion/coupon'
      path: '/promotion/coupon'
      fullPath: '/admin/promotion/coupon'
      preLoaderRoute: typeof AdminPromotionCouponRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/organization/tag': {
      id: '/admin/organization/tag'
      path: '/organization/tag'
      fullPath: '/admin/organization/tag'
      preLoaderRoute: typeof AdminOrganizationTagRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/organization/$orgUuid': {
      id: '/admin/organization/$orgUuid'
      path: '/organization/$orgUuid'
      fullPath: '/admin/organization/$orgUuid'
      preLoaderRoute: typeof AdminOrganizationOrgUuidRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/order/$uuid': {
      id: '/admin/order/$uuid'
      path: '/order/$uuid'
      fullPath: '/admin/order/$uuid'
      preLoaderRoute: typeof AdminOrderUuidRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/instructor/withdrawals': {
      id: '/admin/instructor/withdrawals'
      path: '/instructor/withdrawals'
      fullPath: '/admin/instructor/withdrawals'
      preLoaderRoute: typeof AdminInstructorWithdrawalsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/instructor/revenue': {
      id: '/admin/instructor/revenue'
      path: '/instructor/revenue'
      fullPath: '/admin/instructor/revenue'
      preLoaderRoute: typeof AdminInstructorRevenueRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/instructor/bank-accounts': {
      id: '/admin/instructor/bank-accounts'
      path: '/instructor/bank-accounts'
      fullPath: '/admin/instructor/bank-accounts'
      preLoaderRoute: typeof AdminInstructorBankAccountsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/instructor-applications/$uuid': {
      id: '/admin/instructor-applications/$uuid'
      path: '/instructor-applications/$uuid'
      fullPath: '/admin/instructor-applications/$uuid'
      preLoaderRoute: typeof AdminInstructorApplicationsUuidRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/finance/withdrawals': {
      id: '/admin/finance/withdrawals'
      path: '/finance/withdrawals'
      fullPath: '/admin/finance/withdrawals'
      preLoaderRoute: typeof AdminFinanceWithdrawalsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/finance/revenue': {
      id: '/admin/finance/revenue'
      path: '/finance/revenue'
      fullPath: '/admin/finance/revenue'
      preLoaderRoute: typeof AdminFinanceRevenueRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/finance/platform-fees': {
      id: '/admin/finance/platform-fees'
      path: '/finance/platform-fees'
      fullPath: '/admin/finance/platform-fees'
      preLoaderRoute: typeof AdminFinancePlatformFeesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/finance/payouts': {
      id: '/admin/finance/payouts'
      path: '/finance/payouts'
      fullPath: '/admin/finance/payouts'
      preLoaderRoute: typeof AdminFinancePayoutsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/finance/fee-config': {
      id: '/admin/finance/fee-config'
      path: '/finance/fee-config'
      fullPath: '/admin/finance/fee-config'
      preLoaderRoute: typeof AdminFinanceFeeConfigRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/course/enrollment': {
      id: '/admin/course/enrollment'
      path: '/course/enrollment'
      fullPath: '/admin/course/enrollment'
      preLoaderRoute: typeof AdminCourseEnrollmentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/course/category': {
      id: '/admin/course/category'
      path: '/course/category'
      fullPath: '/admin/course/category'
      preLoaderRoute: typeof AdminCourseCategoryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/course/$courseId': {
      id: '/admin/course/$courseId'
      path: '/course/$courseId'
      fullPath: '/admin/course/$courseId'
      preLoaderRoute: typeof AdminCourseCourseIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/article/create': {
      id: '/admin/article/create'
      path: '/article/create'
      fullPath: '/admin/article/create'
      preLoaderRoute: typeof AdminArticleCreateRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/article/category': {
      id: '/admin/article/category'
      path: '/article/category'
      fullPath: '/admin/article/category'
      preLoaderRoute: typeof AdminArticleCategoryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/article/$articleId': {
      id: '/admin/article/$articleId'
      path: '/article/$articleId'
      fullPath: '/admin/article/$articleId'
      preLoaderRoute: typeof AdminArticleArticleIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/guide/withdrawal/': {
      id: '/admin/guide/withdrawal/'
      path: '/guide/withdrawal'
      fullPath: '/admin/guide/withdrawal/'
      preLoaderRoute: typeof AdminGuideWithdrawalIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/guide/promotion/': {
      id: '/admin/guide/promotion/'
      path: '/guide/promotion'
      fullPath: '/admin/guide/promotion/'
      preLoaderRoute: typeof AdminGuidePromotionIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/guide/featured-course/': {
      id: '/admin/guide/featured-course/'
      path: '/guide/featured-course'
      fullPath: '/admin/guide/featured-course/'
      preLoaderRoute: typeof AdminGuideFeaturedCourseIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/guide/course/': {
      id: '/admin/guide/course/'
      path: '/guide/course'
      fullPath: '/admin/guide/course/'
      preLoaderRoute: typeof AdminGuideCourseIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/promotion/$promotionId/edit': {
      id: '/admin/promotion/$promotionId/edit'
      path: '/promotion/$promotionId/edit'
      fullPath: '/admin/promotion/$promotionId/edit'
      preLoaderRoute: typeof AdminPromotionPromotionIdEditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/course/gradebook/$courseId': {
      id: '/admin/course/gradebook/$courseId'
      path: '/course/gradebook/$courseId'
      fullPath: '/admin/course/gradebook/$courseId'
      preLoaderRoute: typeof AdminCourseGradebookCourseIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminBannersRoute: typeof AdminBannersRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminFeaturedCoursesRoute: typeof AdminFeaturedCoursesRoute
  AdminGalleryRoute: typeof AdminGalleryRoute
  AdminNotificationRoute: typeof AdminNotificationRoute
  AdminProfileRoute: typeof AdminProfileRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminArticleArticleIdRoute: typeof AdminArticleArticleIdRoute
  AdminArticleCategoryRoute: typeof AdminArticleCategoryRoute
  AdminArticleCreateRoute: typeof AdminArticleCreateRoute
  AdminCourseCourseIdRoute: typeof AdminCourseCourseIdRoute
  AdminCourseCategoryRoute: typeof AdminCourseCategoryRoute
  AdminCourseEnrollmentRoute: typeof AdminCourseEnrollmentRoute
  AdminFinanceFeeConfigRoute: typeof AdminFinanceFeeConfigRoute
  AdminFinancePayoutsRoute: typeof AdminFinancePayoutsRoute
  AdminFinancePlatformFeesRoute: typeof AdminFinancePlatformFeesRoute
  AdminFinanceRevenueRoute: typeof AdminFinanceRevenueRoute
  AdminFinanceWithdrawalsRoute: typeof AdminFinanceWithdrawalsRoute
  AdminInstructorApplicationsUuidRoute: typeof AdminInstructorApplicationsUuidRoute
  AdminInstructorBankAccountsRoute: typeof AdminInstructorBankAccountsRoute
  AdminInstructorRevenueRoute: typeof AdminInstructorRevenueRoute
  AdminInstructorWithdrawalsRoute: typeof AdminInstructorWithdrawalsRoute
  AdminOrderUuidRoute: typeof AdminOrderUuidRoute
  AdminOrganizationOrgUuidRoute: typeof AdminOrganizationOrgUuidRoute
  AdminOrganizationTagRoute: typeof AdminOrganizationTagRoute
  AdminPromotionCouponRoute: typeof AdminPromotionCouponRoute
  AdminPromotionCreateRoute: typeof AdminPromotionCreateRoute
  AdminPromotionCreateVoucherRoute: typeof AdminPromotionCreateVoucherRoute
  AdminQuizQuizUuidRoute: typeof AdminQuizQuizUuidRoute
  AdminSettingAppRoute: typeof AdminSettingAppRoute
  AdminSettingNotificationPreferencesRoute: typeof AdminSettingNotificationPreferencesRoute
  AdminSettingPaymentMethodRoute: typeof AdminSettingPaymentMethodRoute
  AdminSettingPlatformRoute: typeof AdminSettingPlatformRoute
  AdminArticleIndexRoute: typeof AdminArticleIndexRoute
  AdminCourseIndexRoute: typeof AdminCourseIndexRoute
  AdminGuideIndexRoute: typeof AdminGuideIndexRoute
  AdminInstructorApplicationsIndexRoute: typeof AdminInstructorApplicationsIndexRoute
  AdminOrderIndexRoute: typeof AdminOrderIndexRoute
  AdminOrganizationIndexRoute: typeof AdminOrganizationIndexRoute
  AdminPromotionIndexRoute: typeof AdminPromotionIndexRoute
  AdminQuizIndexRoute: typeof AdminQuizIndexRoute
  AdminRoleIndexRoute: typeof AdminRoleIndexRoute
  AdminUserIndexRoute: typeof AdminUserIndexRoute
  AdminCourseGradebookCourseIdRoute: typeof AdminCourseGradebookCourseIdRoute
  AdminPromotionPromotionIdEditRoute: typeof AdminPromotionPromotionIdEditRoute
  AdminGuideCourseIndexRoute: typeof AdminGuideCourseIndexRoute
  AdminGuideFeaturedCourseIndexRoute: typeof AdminGuideFeaturedCourseIndexRoute
  AdminGuidePromotionIndexRoute: typeof AdminGuidePromotionIndexRoute
  AdminGuideWithdrawalIndexRoute: typeof AdminGuideWithdrawalIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBannersRoute: AdminBannersRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminFeaturedCoursesRoute: AdminFeaturedCoursesRoute,
  AdminGalleryRoute: AdminGalleryRoute,
  AdminNotificationRoute: AdminNotificationRoute,
  AdminProfileRoute: AdminProfileRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminArticleArticleIdRoute: AdminArticleArticleIdRoute,
  AdminArticleCategoryRoute: AdminArticleCategoryRoute,
  AdminArticleCreateRoute: AdminArticleCreateRoute,
  AdminCourseCourseIdRoute: AdminCourseCourseIdRoute,
  AdminCourseCategoryRoute: AdminCourseCategoryRoute,
  AdminCourseEnrollmentRoute: AdminCourseEnrollmentRoute,
  AdminFinanceFeeConfigRoute: AdminFinanceFeeConfigRoute,
  AdminFinancePayoutsRoute: AdminFinancePayoutsRoute,
  AdminFinancePlatformFeesRoute: AdminFinancePlatformFeesRoute,
  AdminFinanceRevenueRoute: AdminFinanceRevenueRoute,
  AdminFinanceWithdrawalsRoute: AdminFinanceWithdrawalsRoute,
  AdminInstructorApplicationsUuidRoute: AdminInstructorApplicationsUuidRoute,
  AdminInstructorBankAccountsRoute: AdminInstructorBankAccountsRoute,
  AdminInstructorRevenueRoute: AdminInstructorRevenueRoute,
  AdminInstructorWithdrawalsRoute: AdminInstructorWithdrawalsRoute,
  AdminOrderUuidRoute: AdminOrderUuidRoute,
  AdminOrganizationOrgUuidRoute: AdminOrganizationOrgUuidRoute,
  AdminOrganizationTagRoute: AdminOrganizationTagRoute,
  AdminPromotionCouponRoute: AdminPromotionCouponRoute,
  AdminPromotionCreateRoute: AdminPromotionCreateRoute,
  AdminPromotionCreateVoucherRoute: AdminPromotionCreateVoucherRoute,
  AdminQuizQuizUuidRoute: AdminQuizQuizUuidRoute,
  AdminSettingAppRoute: AdminSettingAppRoute,
  AdminSettingNotificationPreferencesRoute:
    AdminSettingNotificationPreferencesRoute,
  AdminSettingPaymentMethodRoute: AdminSettingPaymentMethodRoute,
  AdminSettingPlatformRoute: AdminSettingPlatformRoute,
  AdminArticleIndexRoute: AdminArticleIndexRoute,
  AdminCourseIndexRoute: AdminCourseIndexRoute,
  AdminGuideIndexRoute: AdminGuideIndexRoute,
  AdminInstructorApplicationsIndexRoute: AdminInstructorApplicationsIndexRoute,
  AdminOrderIndexRoute: AdminOrderIndexRoute,
  AdminOrganizationIndexRoute: AdminOrganizationIndexRoute,
  AdminPromotionIndexRoute: AdminPromotionIndexRoute,
  AdminQuizIndexRoute: AdminQuizIndexRoute,
  AdminRoleIndexRoute: AdminRoleIndexRoute,
  AdminUserIndexRoute: AdminUserIndexRoute,
  AdminCourseGradebookCourseIdRoute: AdminCourseGradebookCourseIdRoute,
  AdminPromotionPromotionIdEditRoute: AdminPromotionPromotionIdEditRoute,
  AdminGuideCourseIndexRoute: AdminGuideCourseIndexRoute,
  AdminGuideFeaturedCourseIndexRoute: AdminGuideFeaturedCourseIndexRoute,
  AdminGuidePromotionIndexRoute: AdminGuidePromotionIndexRoute,
  AdminGuideWithdrawalIndexRoute: AdminGuideWithdrawalIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface StudentRouteChildren {
  StudentDashboardRoute: typeof StudentDashboardRoute
  StudentNotificationRoute: typeof StudentNotificationRoute
  StudentNotificationSettingsRoute: typeof StudentNotificationSettingsRoute
  StudentProfileRoute: typeof StudentProfileRoute
  StudentSettingsRoute: typeof StudentSettingsRoute
  StudentWishlistRoute: typeof StudentWishlistRoute
  StudentLearnCourseUuidRoute: typeof StudentLearnCourseUuidRoute
  StudentOrderUuidRoute: typeof StudentOrderUuidRoute
  StudentOrderIndexRoute: typeof StudentOrderIndexRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentDashboardRoute: StudentDashboardRoute,
  StudentNotificationRoute: StudentNotificationRoute,
  StudentNotificationSettingsRoute: StudentNotificationSettingsRoute,
  StudentProfileRoute: StudentProfileRoute,
  StudentSettingsRoute: StudentSettingsRoute,
  StudentWishlistRoute: StudentWishlistRoute,
  StudentLearnCourseUuidRoute: StudentLearnCourseUuidRoute,
  StudentOrderUuidRoute: StudentOrderUuidRoute,
  StudentOrderIndexRoute: StudentOrderIndexRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AksesibilitasRoute: AksesibilitasRoute,
  ArticleRoute: ArticleRoute,
  BecomeAnInstructorRoute: BecomeAnInstructorRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ClientRoute: ClientRoute,
  DebugAuthRoute: DebugAuthRoute,
  DevRoute: DevRoute,
  HubungiKamiRoute: HubungiKamiRoute,
  KebijakanPrivasiRoute: KebijakanPrivasiRoute,
  LoginRoute: LoginRoute,
  LoginNewRoute: LoginNewRoute,
  RegisterRoute: RegisterRoute,
  SearchRoute: SearchRoute,
  SearchOldRoute: SearchOldRoute,
  StudentRoute: StudentRouteWithChildren,
  SyaratKetentuanRoute: SyaratKetentuanRoute,
  TentangKamiRoute: TentangKamiRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  CategoriesSlugRoute: CategoriesSlugRoute,
  CourseCourseSlugRoute: CourseCourseSlugRoute,
  VerifyUuidRoute: VerifyUuidRoute,
  B2bActivateInvitationUuidRoute: B2bActivateInvitationUuidRoute,
  CertificateVerifyUuidRoute: CertificateVerifyUuidRoute,
  CertificateVerifyPreviewRoute: CertificateVerifyPreviewRoute,
  InstructorApplyStatusRoute: InstructorApplyStatusRoute,
  InstructorApplyIndexRoute: InstructorApplyIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
